# Custom Health Chatbot

In [586]:
#pip install -U google-genai

In [587]:
#export GEMINI_API_KEY="AIzaSyDf5Qxq-MhDyknal2xXMM3L93nfkVk5OA4"

In [623]:
import pandas as pd
from google import genai
from google.genai import types
import json
import os
import re

from flask import Flask, render_template, request

In [589]:
client = genai.Client(api_key="AIzaSyDf5Qxq-MhDyknal2xXMM3L93nfkVk5OA4")
print(client)

<google.genai.client.Client object at 0x7fcb28e8c820>

In [590]:
# models = client.models.list()

# for model in models:
#     print(model.name)

In [591]:
health = pd.read_csv("/Users/Sanju/Desktop/health_ai/Health_dataset_1.csv")
lifestyle = pd.read_csv("/Users/Sanju/Desktop/health_ai/Health_dataset_2.csv")

In [592]:
health.head(5)

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1.0,0,48071,NaN,2,1,1
1,2,0,9.75,0.23,54,33,1,NaN,0,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,NaN,0,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,NaN,0,7439,242.0,1,0,0
4,5,1,14.17,0.83,52,19,0,NaN,0,49644,397.0,2,0,0

In [593]:
lifestyle.head(5)

   Patient_Number  Day_Number  Physical_activity
0               1           1            23590.0
1               1           2            10411.0
2               1           3             7815.0
3               1           4            12366.0
4               1           5                NaN

In [594]:
def quick_audit(df):
    return pd.DataFrame({
        "dtype": df.dtypes,
        "missing_%": df.isna().mean() * 100,
        "unique_vals": df.nunique()
    })

quick_audit(health)

                                 dtype  missing_%  unique_vals
Patient_Number                   int64        0.0         2000
Blood_Pressure_Abnormality       int64        0.0            2
Level_of_Hemoglobin            float64        0.0          757
Genetic_Pedigree_Coefficient   float64        4.6          101
Age                              int64        0.0           58
BMI                              int64        0.0           41
Sex                              int64        0.0            2
Pregnancy                      float64       77.9            2
Smoking                          int64        0.0            2
salt_content_in_the_diet         int64        0.0         1945
alcohol_consumption_per_day    float64       12.1          488
Level_of_Stress                  int64        0.0            3
Chronic_kidney_disease           int64        0.0            2
Adrenal_and_thyroid_disorders    int64        0.0            2

In [595]:
quick_audit(lifestyle)

                     dtype  missing_%  unique_vals
Patient_Number       int64      0.000         2000
Day_Number           int64      0.000           10
Physical_activity  float64     19.205        12878

In [596]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.strip() # Removes trailing spaces
        .str.lower() # All column names are now lowercase
        .str.replace(" ","_")
    )
    return df

health_df = clean_columns(health)
lifestyle_df = clean_columns(lifestyle)

In [597]:
quick_audit(lifestyle_df)

                     dtype  missing_%  unique_vals
patient_number       int64      0.000         2000
day_number           int64      0.000           10
physical_activity  float64     19.205        12878

For numerical columns:
“I use median imputation for numerical health features because it’s robust to outliers and clinically safer than mean.”

In [598]:
# Fixing the missing values

num_cols = health_df.select_dtypes(include = "number").columns
category_cols = health_df.select_dtypes(exclude="number").columns

health_df[num_cols] = health_df[num_cols].fillna(health_df[num_cols].median())
health_df[category_cols] = health_df[category_cols].fillna("unknown")

In [599]:
#Lets fix categorical columns

def clean_categories(df):
    for col in df.select_dtypes(exclude = "number"):
        df[col]=df[col].str.lower().str.strip()
    return df

health_df = clean_categories(health_df)
lifestyle_df = clean_categories(lifestyle_df)

health_df.head()

,patient_number,blood_pressure_abnormality,level_of_hemoglobin,genetic_pedigree_coefficient,age,bmi,sex,pregnancy,smoking,salt_content_in_the_diet,alcohol_consumption_per_day,level_of_stress,chronic_kidney_disease,adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1.0,0,48071,250.0,2,1,1
1,2,0,9.75,0.23,54,33,1,0.0,0,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,0.0,0,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,0.0,0,7439,242.0,1,0,0
4,5,1,14.17,0.83,52,19,0,0.0,0,49644,397.0,2,0,0

In [600]:
assert health_df["patient_number"].is_unique

In [601]:
#Lets go ahead create a DB and add these as tables for LLM to use

import sqlite3

conn = sqlite3.connect("health.db")

health_df.to_sql("health",conn,if_exists="replace",index=False)
lifestyle_df.to_sql("lifestyle",conn,if_exists="replace",index=False)

20000

# Step 2
### We now move on to dealing with how to the feed data to LLM.

In [602]:
# Extract SQL Schema as LLM only reads schema and not data.

def sql_schema(conn):
    query = """
    SELECT name, sql
    FROM sqlite_master
    WHERE type = 'table';
    """
    return pd.read_sql(query,conn)

schema_df = sql_schema(conn)
schema_df

        name                                                sql
0     health  CREATE TABLE "health" (\n"patient_number" INTE...
1  lifestyle  CREATE TABLE "lifestyle" (\n"patient_number" I...

In [603]:
# Convert the schema to prompt text for LLM to understand

def format_schema_for_llm(schema_df):
    return "\n\n".join(schema_df["sql"].tolist())

schema_text = format_schema_for_llm(schema_df)
print(schema_text)

CREATE TABLE "health" (
"patient_number" INTEGER,
  "blood_pressure_abnormality" INTEGER,
  "level_of_hemoglobin" REAL,
  "genetic_pedigree_coefficient" REAL,
  "age" INTEGER,
  "bmi" INTEGER,
  "sex" INTEGER,
  "pregnancy" REAL,
  "smoking" INTEGER,
  "salt_content_in_the_diet" INTEGER,
  "alcohol_consumption_per_day" REAL,
  "level_of_stress" INTEGER,
  "chronic_kidney_disease" INTEGER,
  "adrenal_and_thyroid_disorders" INTEGER
)

CREATE TABLE "lifestyle" (
"patient_number" INTEGER,
  "day_number" INTEGER,
  "physical_activity" REAL
)

In [604]:
# Lets define Strict prompt for LLM

SYSTEM_PROMPT = """
You are a data assistant.
Given a user question and a database schema, decide the correct execution method
and generate either a SQL query or Python code.

EXECUTION DECISION:
- If the task can be solved using SQLite-compatible SQL, generate SQL
- If the task requires correlation, regression, or statistical computation
  that SQLite does NOT support, generate Python instead

PYTHON RULES (if language = "python"):
- Operate ONLY on a pandas DataFrame named `df`
- Assume `df` already contains all required columns
- Do NOT import libraries
- Do NOT access files, OS, network, or external resources
- Assign the final result to a variable (e.g., corr, result)
- ALSO provide a SQL query to construct the DataFrame `df`
- The Python code will execute ONLY on this DataFrame

Output format (Strictly JSON only):
For SQL:
{
  "language": "sql",
  "query": "SQL QUERY HERE"
}

For Python:
{
  "language": "python",
  "query": "SQL QUERY TO BUILD df",
  "code": "PYTHON CODE to execute on df"
}
"""

In [605]:
# Lets pass system prompt, schema and user question as input to LLM

def build_llm_input(SYSTEM_PROMPT,schema_text,user_question):
    return f"""
{SYSTEM_PROMPT}

DATABASE SCHEMA:
{schema_text}

USER QUESTION:
{user_question}

"""

In [ ]:
# Defining a default user question for now
#user_question = "Is physical activity associated with BMI?"

llm_input = build_llm_input(
    SYSTEM_PROMPT,
    schema_text,
    user_question
)

Why mock first?

Because:

- You want to test joins

- You want to test execution

- You want deterministic output

LLMs come later.

In [607]:
# Mock LLM Call

# def mock_llm(llm_input: str) -> dict:
#     """
#     Simulates LLM output for development and testing.
#     Returns strict JSON as per SYSTEM PROMPT.
#     """
#     return {
#         "language": "sql",
#         "query": """
#         SELECT AVG(h.bmi) AS avg_bmi,AVG(l.physical_activity) AS avg_activity
#         FROM health h
#         JOIN lifestyle l
#         ON h.patient_number = l.patient_number;
#         """
#     }

In [608]:
def safe_json_parse(text: str) -> dict:
    """
    Extracts the first JSON object found in text and parses it.
    """
    match = re.search(r"\{.*\}", text, re.S)
    if not match:
        raise ValueError(f"No JSON found in LLM output:\n{text}")
    return json.loads(match.group())

## LLM 1 (SQL / Python Generator)

In [609]:
def generate_plan_llm(llm_input:str)-> dict:
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=llm_input
    )
    return safe_json_parse(response.text)

In [610]:
# # Call mock LLM

# llm_output = mock_llm(llm_input)

# llm_output

### So till now we have used LLM to generate a sql code based on query and then converted it into a JSON format.
### There are two LLM's
## LLM (Sql generator) : 
- Reads only data schema and not dataset (No data leakage, hence less hallucination)
- Return SQL code

## LLM 2 (Reviewer)
- Recieves the JSON code and makes decisions
- Retruns just the curated answer to user.

# SQL/Python Validation and Sandbox execution

In [611]:
# Lets first validate the sql input as LLM 1 output could be not blindly trusted

def validate_sql(query: str):
    forbidden = {"insert","update","delete","truncate","drop","alter"}

    q = query.strip().lower()

    assert q.startswith("select"), "Only SELECT queries are allowed "
    
    for word in forbidden:
        assert word not in q, f"Forbidden word : {word} is detected"

In [612]:
# This validate python to avoid loops of "for" or "while"
def validate_python(code: str):
    forbidden = [
        "import",
        "__",
        "open(",
        "exec(",
        "eval(",
        "os.",
        "sys.",
        "subprocess",
        "socket",
        "requests",
        "while",
        "for"
    ]

    for token in forbidden:
        assert token not in code.lower(), f"Forbidden Python token detected: {token}"

In [613]:
# Now run the query with conn created in sqlite3

def run_sql(query,conn):
    return pd.read_sql(query,conn)

In [614]:
def run_python(code: str, df: pd.DataFrame):
    safe_globals = {
        "__builtins__": {},
        "df": df
    }
    safe_locals = {}
    exec(code, safe_globals, safe_locals)
    return safe_locals

In [615]:
# # Calling the functions

# llm_output = generate_plan_llm(llm_input)

# if llm_output["language"] == "sql":
#     validate_sql(llm_output["query"])
#     df = run_sql(llm_output["query"], conn)

# elif llm_output["language"] == "python":
#     # Step 1: Build df
#     validate_sql(llm_output["query"])
#     df = run_sql(llm_output["query"], conn)

#     # Step 2: Run Python on df
#     validate_python(llm_output["code"])
#     result = run_python(llm_output["code"], df)

## These are commented cause we will call them again below.

# Now the LLM will study and give us the insight

## SQL based insighter

In [ ]:
# Lets define the LLM to strictly give back insights based on data

def build_sql_insight(user_question,result_df):
    return f"""
You are a health analytics assistant.

User question:
{user_question}

Computed results:
{result_df.to_dict(orient="records")}

Rules:
- Base conclusions ONLY on the provided results
- Do NOT introduce new data
- Avoid medical diagnosis
- Provide descriptive insights only
- Frame answers as population-level insights, not personal outcomes
"""

## Python based insighter

In [ ]:
def build_python_insight(user_question, python_result):
    return f"""
You are a health analytics assistant.

User question:
{user_question}

Computed result:
{python_result}

Rules:
- Explain the result in simple, user-friendly language
- Clearly state whether the relationship is strong, weak, or negligible
- Avoid statistical jargon unless necessary
- Do NOT mention exact coefficient values unless helpful
- Do NOT provide medical diagnosis or advice

Response style:
- Greet the user first.
- Explain in plain english within hundred words in paragraph.
- Include percentages if required.
- Do not explain the relationships, just answer in comaprison terms.
- Focus on practical interpretation
- Recommend the user to Consult the Doctor for professional advice.
- Frame answers as population-level insights, not personal outcomes
"""

## LLM 2 (Insights)

In [618]:
def generate_insight_llm(insight_prompt: str) -> str:
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=insight_prompt
    )
    return response.text

In [619]:
# 1. LLM generates execution plan (SQL or Python)
llm_output = generate_plan_llm(llm_input)

# 2. Execute based on language
if llm_output["language"] == "sql":
    # --- SQL path ---
    validate_sql(llm_output["query"])
    result_df = run_sql(llm_output["query"], conn)

    # Build insight prompt from DataFrame
    insight_prompt = build_sql_insight(
        user_question,
        result_df
    )

elif llm_output["language"] == "python":
    # --- Python path ---
    # Step 1: SQL to build df
    validate_sql(llm_output["query"])
    result_df = run_sql(llm_output["query"], conn)

    # Step 2: Python computation
    validate_python(llm_output["code"])
    python_result = run_python(llm_output["code"], result_df)

    # Build insight prompt from Python result
    insight_prompt = build_python_insight(
        user_question,
        python_result
    )
# Step 3: Generate insight
final_answer = generate_insight_llm(insight_prompt)

# Add the Evaluation Metrics

We add it to keep the LLM grounded and not give confident decisions keeping it based on the result df and not random.

In [620]:
# Checking Groundedness

def check_groundedness(answer, result_keys):
    return all(key in answer.lower() for key in result_keys) # This checks if the answer statement has keywords of result_keys, determines that answer is not hallucinated.

In [621]:
# We know add the code if the question is unsuppprted to the schema
def unsupported_query_guard(schema_text, user_question):
    keywords = ["smoking", "alcohol", "diet"]
    return any(k in user_question.lower() for k in keywords) and "smoking" not in schema_text

In [622]:
print(final_answer)

Hello!

Based on our analysis, there appears to be a very weak, almost negligible connection between physical activity and BMI. This means that, for the data we looked at, changes in physical activity are not strongly associated with changes in BMI. In practical terms, there isn't a clear or significant trend indicating that higher physical activity levels consistently correspond with a specific BMI outcome, or vice-versa, when considering these two factors alone. Please consult your doctor for personalized health advice.

# Lets now Build the Flask App

In [ ]:
app = Flask("Health AI assitant")

@app.route("/", methods=["GET","POST"])
def index():
    answer = None
    error = None
    if request.method == "POST":
        try:
            # Get user question
            user_question = request.form["question"]

            #Build LLM input
            llm_input = build_llm_input(
                SYSTEM_PROMPT,
                schema_text,
                user_question
            )
            # Generate execution plan (SQL or Python)
            llm_output = generate_plan_llm(llm_input)

            #Exexute the plan
            if llm_output["language"] == "sql":
                validate_sql(llm_output["query"])
                result_df = run_sql(llm_output["query"], conn)

                insight_prompt = build_sql_insight_prompt(
                    user_question,
                    result_df
                )
            elif llm_output["language"] == "python":
                validate_sql(llm_output["query"])
                result_df = run_sql(llm_output["query"], conn)

                validate_python(llm_output["code"])
                python_result = run_python(
                    llm_output["code"],
                    result_df
                )
                insight_prompt = build_python_insight_prompt(
                    user_question,
                    python_result
                )
            else:
                error = "Unsupported execution type."

            # Generate final insight

            if insight_prompt:
                answer = generate_insight_llm(insight_prompt)
        
        except Exception as e:
            error = str(e)

    #Render the UI
    return render_template(
        "index.html",
        answer=answer,
        error=error
    )

# Rn the App

if __name__ == "__main__":
    app.run(debug=True)